### PR TITLE
bump build-scripts to 1.56

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by jrha** [comment]
@hpcugentbot test this please

**Comment by jrha** [comment]
```
Undefined subroutine &main::set_caf_file_close_diff called at src/test/perl/configure.t line 1175.
```
???
:confused:

**Comment by stdweird** [comment]
@jrha i'm cleaning them up. no worries 😉

**Comment by stdweird** [comment]
@jrha 📗

**Pull request merged**
