### PR TITLE
Remove ncm-gold component

### PR DESCRIPTION
**Pull request by stdweird**
Component is not used and could be replaced by metaconfig.
Gold is the "Gold Allocation Manager" (http://docs.adaptivecomputing.com/gold/), an accoutning system for maui/moab.

### CODE REVIEW

**Comment by jouvin** [comment]
I am not sure what `ncm-gold` was doing... but a short description saying why it is removed would be good! After this is done and conflicts are solved, I am happy to merge it.

**Comment by jrha** [comment]
Removal agreed at workshop (as long as @jouvin's comments are addressed)

**Comment by stdweird** [comment]
@jouvin sufficicent explanation?

**Comment by jouvin** [comment]
Yes, LGTM. Merging...

**Pull request merged**
