### PR TITLE
ncm-xrootd: add ability to manage sec.protocol options

### PR DESCRIPTION
**Pull request by jouvin**
This includes an enhancement of the rule-based editor in order to be able to build a configuration line from hash entries.

Note: this version of the configuration module must not be used without the (upcoming) template-library-grid PR that will define the appropriate configuration params by default. Else it will result in removing the `sec.protocol` line from the configuration file if it exists.

### CODE REVIEW

**Comment by jouvin** [comment]
As usual, the rule-based editor being duplicated between `ncm-xrootd` and `ncm-dpmlfc`up to now, this includes a modification to the version used by `ncm-dpmlfc` (identical) and to relevant unit tests (rule-based editor unit testing is currently done in `ncm-dpmlfc`). But the new version doesn't bring any change to `ncm-dpmlfc` itself.

**Comment by jrha** [comment]
I've bumped this to 16.4 as I have seen no sign of the required change to template-library-grid that was mentioned.

**Comment by jouvin** [comment]
You are right, I must check what I wanted to say!!

**Comment by jouvin** [comment]
My fault not having following up this PR. It is no longer possible to merge it as it is because it contains some modifications to the RuleBasedEditor now moved to CAF. I'll try to update everything during the WE. And check what is needed on the template side.

**Comment by jouvin** [comment]
For clarity, closing this PR and opening a new one.

**Pull request closed without merging**
