### PR TITLE
ncm-dpmlfc: fix rules to generate /etc/shift.conf

### PR DESCRIPTION
**Pull request by jouvin**
This PR is a fix for a problem affected `ncm-dpmlfc` only, discovered just after 15.12 release. The issue is an incomplete contents for `/etc/shift.conf` file managed by the component. As a result, RFIO-based `dpm-drain` (<= DPM 1.8.9) is broken.

Solving properly this issue involved improving the processing of arrays in the rule-based editor. The `ncm-xroot` copy of it has been updated too.

Unit tests have been improved to cover the new use cases and to display the debug messages with `prove.args=-v`.

### CODE REVIEW

**Comment by jrha** [comment]
Given you pressured me into including #86 in 15.12 I'm a bit annoyed about this.
Once this is merged I can drop a hot-fix RPM into the 15.12 repository and fudge things.
I assume this has been tested at LAL?

**Comment by jouvin** [comment]
I was annoyed too! This was easy to miss in fact... This is always the same story with tests: you need to think about all the different things that need to be tested (this is more a functional than a unit test) and it is easy to miss something. Nevertheless this is not a major problem: it doesn't break a working DPM installation. drain is a quite exceptional operation and it is not that difficult to upgrade the component.
I would personnally be in favour of keeping 15.12 and avoid to fludge: it's a too bad practice. I would propose the 13.1.4 approach:
- put the SNAPSHOT RPM containing the fix either in the 15.12.0 repo if it doesn't pose a problem (but it may because of signatures) or in the Quattor externals repository
- Do a 15.12.1 release (tag) in template-library-core with the updated templates to use the snapshot version. Alternatively, we could just put the templates somewhere and ask people to update their 15.12.0 templates with them. 

It may be that nobody really cares about this fix except LAL...

**Comment by jouvin** [comment]
@Pansanel or @guillaume-philippon is it possible to merge this PR?

**Comment by jouvin** [comment]
@Pansanel or @guillaume-philippon  ???

**Comment by Pansanel** [comment]
The code seems ok, but I can not test it now. Is this code already in prod at LAL?

**Comment by jouvin** [comment]
Yes, I should have been more clear about it.

**Pull request merged**
